[package]
name = "contracts"
version = "0.2.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
# Change to just "openzeppelin" to use full features
openzeppelin_access = "0.17.0"
openzeppelin_token = "0.17.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib.git"}

[dev-dependencies]
openzeppelin_utils = "0.17.0"
snforge_std = "0.30.0"


[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "TEST"
url = "https://rpc.nethermind.io/mainnet-juno/?apikey=Zh5vBpotTbH8DlbCyWqyuQHARB2O5A2gGVck3gzBNXkXlqAP"
block_id.number = "649020"
