version: "3"

services:
  devnet:
    image: shardlabs/starknet-devnet-rs:d9ce83c4a5b0907fe201496d8cb3b89dc626cb9c-seed0
    command:
      - --dump-on=exit
      - --dump-path=/data/dump
      - --fork-network=https://rpc.nethermind.io/mainnet-juno/rpc/v0_7?apikey=<APIKEY>
    volumes:
      - devnet:/data
    ports:
      - 5050:5050

  dna:
    image: quay.io/apibara/starknet
    command:
      - start
      - --rpc=http://devnet:5050/rpc
      - --name=devnet
      - --head-refresh-interval-ms=1000
      - --wait-for-rpc
      - --address=0.0.0.0:7171
      - --dangerously-override-ingestion-start-block=898557
    environment:
      - XDG_DATA_HOME=/data
    volumes:
      - dna:/data
    ports:
      - 7171:7171
    depends_on:
      devnet:
        condition: service_started

volumes:
  devnet:
  dna: